SELECT distinct USER_ID, PRODUCT_ID
FROM ONLINE_SALE a
WHERE EXISTS (
    SELECT 1
    FROM ONLINE_SALE b
    WHERE a.USER_ID = b.USER_ID
      AND a.PRODUCT_ID = b.PRODUCT_ID
      AND a.ONLINE_SALE_ID != b.ONLINE_SALE_ID
)
order by USER_ID, PRODUCT_ID desc
