SELECT A.PRODUCT_CODE, (A.PRICE * B.SALES_AMOUNT) AS SALES
FROM
PRODUCT A JOIN 
(SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT  FROM OFFLINE_SALE GROUP BY PRODUCT_ID) B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY SALES DESC, A.PRODUCT_CODE	



















# -- 코드를 입력하세요
# SELECT PRODUCT_CODE, SUM(PRODUCT.PRICE * OFFLINE_SALE.SALES_AMOUNT) AS SALES

# FROM PRODUCT JOIN OFFLINE_SALE ON PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
# GROUP BY OFFLINE_SALE.PRODUCT_ID

# ORDER BY SALES DESC, PRODUCT_CODE