
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE,START_DATE)+1), 1) AS 'AVERAGE_DURATION'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >=7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC












# SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE,START_DATE)+1), 1) AS AVERAGE_DURATION
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID
# HAVING AVG(DATEDIFF(END_DATE,START_DATE)+1) >= 7
# ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;






-- 코드를 입력하세요
# SELECT CAR_ID, round(avg(END_DATE - START_DATE), 1) as AVERAGE_DURATION
# from CAR_RENTAL_COMPANY_RENTAL_HISTORY
# where (select avg(END_DATE - START_DATE)) >=7 
# group by CAR_ID
# order by AVERAGE_DURATION desc, CAR_ID desc


# SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE,START_DATE)+1), 1) AS AVERAGE_DURATION
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID
# HAVING AVG(DATEDIFF(END_DATE,START_DATE)+1) >= 7
# ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;