-- 코드를 작성해주세요
SELECT YEAR(A.DIFFERENTIATION_DATE) as YEAR, B.m - A.SIZE_OF_COLONY as YEAR_DEV, A.ID
FROM ECOLI_DATA A, (select MAX(SIZE_OF_COLONY) as m , YEAR(DIFFERENTIATION_DATE) as y from ECOLI_DATA group by YEAR(DIFFERENTIATION_DATE)) B
where YEAR(A.DIFFERENTIATION_DATE) = B.y
order by YEAR, YEAR_DEV
