SELECT 
    YEAR(a.DIFFERENTIATION_DATE) AS year,
    (b.max_size - a.SIZE_OF_COLONY) AS YEAR_DEV,
    a.ID
FROM ECOLI_DATA a
JOIN (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS year,
        MAX(SIZE_OF_COLONY) AS max_size
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) b 
ON YEAR(a.DIFFERENTIATION_DATE) = b.year
order by YEAR asc, YEAR_DEV asc
