-- 코드를 작성해주세요
SELECT SUM(A.COUNT) AS FISH_COUNT
FROM(
    SELECT COUNT(*) AS COUNT
FROM FISH_INFO F, FISH_NAME_INFO N
WHERE N.FISH_TYPE = F.FISH_TYPE AND N.FISH_NAME IN('BASS', 'SNAPPER')
GROUP BY F.FISH_TYPE
) A
