SELECT COUNT(*) AS FISH_NAME_INFO
FROM FISH_INFO A JOIN FISH_NAME_INFO B ON
A.FISH_TYPE = B.FISH_TYPE
WHERE FISH_NAME IN ('SNAPPER', 'BASS')
















# SELECT COUNT(*) as 'SNAPPER'
# FROM (
#   SELECT FISH_TYPE, COUNT(*) AS CNT
#   FROM FISH_INFO
#   GROUP BY FISH_TYPE
# ) a
# JOIN (
#   SELECT FISH_TYPE
#   FROM FISH_NAME_INFO
#   WHERE FISH_NAME = 'SNAPPER'
# ) b
# ON a.FISH_TYPE = b.FISH_TYPE;




# # SELECT COUNT(*) AS FISH_COUNT 
# # FROM FISH_INFO
# # WHERE FISH_TYPE	IN (SELECT FISH_TYPE FROM FISH_NAME_INFO WHERE FISH_NAME = 'BASS' OR FISH_NAME = 'SNAPPER')