-- 코드를 작성해주세요
SELECT A.DEPT_ID, A.DEPT_NAME_EN, B.AV AS AVG_SAL
FROM HR_DEPARTMENT A 
JOIN
(SELECT DEPT_ID, ROUND(AVG(SAL), 0) AS AV
FROM HR_EMPLOYEES
GROUP BY DEPT_ID) B
ON A.DEPT_ID = B.DEPT_ID
ORDER BY AVG_SAL DESC