-- 코드를 입력하세요
# BOARD테이블에서 조회수가 가장 높은 중고거래 게시물에 대한 첨부파일 경로

SELECT 
CONCAT('/home/grep/src/', A.BOARD_ID, '/',A.FILE_ID, A.FILE_NAME, A.FILE_EXT)
AS FILE_PATH
FROM USED_GOODS_FILE A JOIN
(SELECT BOARD_ID, VIEWS FROM
    USED_GOODS_BOARD 
 WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
) B 
ON A.BOARD_ID = B.BOARD_ID 
ORDER BY A.FILE_ID DESC